### ISSUE TITLE
Doable in python ?

### ISSUE THREAD

**Issue by SecT0uch** [ross-weir/x64dbg_rc#2]
I don't know much about C++ programming, and windows environnement and was wondering if the example could be reproduced in python with pywin32 ?

I successfully get the window, but I'm not sure on how to get SendMessage's lparam right:

```python
import win32gui
import win32con
import sys


window = win32gui.FindWindow("Qt5QWindowIcon", "x32dbg")  # 0 if no window found

if not window:
    window = win32gui.FindWindow("Qt5QWindowIcon", "x64dbg")  # 0 if no window found
    if not window:
        sys.exit("Make sure x64dbg (or x32dbg) is running")


command = b'log TEEEEST'


res = win32gui.SendMessage(window, win32con.WM_COPYDATA , None , lparam)

```

What type/value `lparam` should be ?
I've tried [several methods](https://stackoverflow.com/questions/19886633/sending-wm-copydata-with-python-3) using `arrays`, `struct` and `ctypes` with no success.

The built executable works like a charm.

**Comment by ross-weir** [comment]
Yep, I added an example using python + `ctypes`: https://github.com/ross-weir/x64dbg_rc/blob/cmake/examples/python/main.py

Hopefully it's helpful

**Comment by SecT0uch** [comment]
Superb thanks ! :)
